// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQqsEVGRplNX1yTTTCEiyNaLNfRHNGn1g',
    appId: '1:1052430642596:web:a643f117ec9e5c6c392531',
    messagingSenderId: '1052430642596',
    projectId: 'centry1777',
    authDomain: 'centry1777.firebaseapp.com',
    storageBucket: 'centry1777.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCr0sZQsXTV1vYoP-DPR5ew7xEXIn2aOA',
    appId: '1:1052430642596:android:1b093d15b6f549bb392531',
    messagingSenderId: '1052430642596',
    projectId: 'centry1777',
    storageBucket: 'centry1777.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfsWb2Y702UIt9HC7ZaQqa8Zcsv3W5idM',
    appId: '1:1052430642596:ios:2ff41b7c75830f83392531',
    messagingSenderId: '1052430642596',
    projectId: 'centry1777',
    storageBucket: 'centry1777.firebasestorage.app',
    iosBundleId: 'com.centry.mobile.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfsWb2Y702UIt9HC7ZaQqa8Zcsv3W5idM',
    appId: '1:1052430642596:ios:a2912e8525a86d0f392531',
    messagingSenderId: '1052430642596',
    projectId: 'centry1777',
    storageBucket: 'centry1777.firebasestorage.app',
    iosBundleId: 'website.centry.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQqsEVGRplNX1yTTTCEiyNaLNfRHNGn1g',
    appId: '1:1052430642596:web:3a69e33c2806f70e392531',
    messagingSenderId: '1052430642596',
    projectId: 'centry1777',
    authDomain: 'centry1777.firebaseapp.com',
    storageBucket: 'centry1777.firebasestorage.app',
  );
}
